OHHTTPStubs/OHHTTPStubs.xcodeproj/project.pbxproj, OHHTTPStubs/OHHTTPStubs.xcodeproj/xcshareddata/xcschemes/OHHTTPStubs iOS Framework.xcscheme
Could not install OHHTTPStubs using Carthage if iOS 7 simulator is installed. The cause of failure is `xcodebuild` misunderstands deployment target as 6.0, which is from OHHTTPStubs iOS Tests, so I separate tests target for iOS framework from OHHTTPStubs iOS Tests. This might be a bug of `xcodebuild`, but we need a workaround for now.
NOTE: this is not bug of Carthage because this can be reproduced by `xcodebuild -scheme "OHHTTPStubs iOS Framework" -workspace OHHTTPStubsDemo.xcworkspace`.
Cartfile:
```
github "AliSoftware/OHHTTPStubs" "master"
```
Output:
```
*** Fetching OHHTTPStubs
*** Checking out OHHTTPStubs at "02cc9fcc0cdfca79e1968df9e3e072c256e5e593"
*** xcodebuild output can be found in /var/folders/0j/p83b0p397sz3y910bvz9_1wh0000gn/T/carthage-xcodebuild.LTKmmE.log
*** Building …
```
=> Fix Carthage support

OHHTTPStubs/Sources/OHHTTPStubs.m, OHHTTPStubs/UnitTests/Test Suites/AFNetworkingTests.m, OHHTTPStubs/UnitTests/Test Suites/NSURLConnectionDelegateTests.m
Treats status code 300 'multiple choices' like a 2xx code to give the user agent a chance to select the redirect url.
Relates to issue #91
=> Handle HTTP status code 300 differently than other redirect codes.

OHHTTPStubs/OHHTTPStubs.xcodeproj/project.pbxproj, OHHTTPStubs/Sources/OHPathHelpers.m, OHHTTPStubs/UnitTests/OHPathHelpersTests.m
`OHResourceBundle` did not work anymore because the function definition in the header did not match the name in the implementation.
=> Fix `OHResourceBundle` name mismatch between header and implementation

OHHTTPStubs/Sources/Mocktail/OHHTTPStubs+Mocktail.h, OHHTTPStubs/Sources/Mocktail/OHHTTPStubs+Mocktail.m, OHHTTPStubs/UnitTests/Test Suites/MocktailTests.m
This is an effort to support stubbing the network requests using files in the format of Mocktail(see more at: https://github.com/square/objc-mocktail). Mocktail is a popular format of network mocking which contains every piece of information in order to mock/stub a network request. By supporting this format, first, we will be able to allow Mocktail users to convert to OHHTTPStatus; Secondly, we will be able to add other functionalities to OHHTTPStatus, for example, recording traffic in the format of Mocktail and later on use it for stubbing.
=> Stub network requests easily with Mocktail files/folders

OHHTTPStubs/Sources/OHHTTPStubsResponse.h, OHHTTPStubs/Sources/OHHTTPStubsResponse.m
@AliSoftware please let me know if you need any changes to this.
Thanks in advance
=> Add in new slower download speed constants 1.0 and 1.5 kbps

OHHTTPStubs/OHHTTPStubs.xcodeproj/project.pbxproj
=> fix issue 117

CHANGELOG.md, OHHTTPStubs/Sources/OHHTTPStubsResponse.h, OHHTTPStubs/Sources/OHHTTPStubsResponse.m, OHHTTPStubs/UnitTests/Test Suites/NilValuesTests.m, Rakefile
iOS 4 allowed using `NSURL`s instead of `NSString`s for file paths. This PR allows using `NSURL`s to create `OHHTPStubResponse`s, which provides better compatibility with test code already using `NSURL`s.
I copied each test using `responseWithFileAtPath:statusCode:headers:` and used `responseWithURL:statusCode:headers:` there instead. This ends up duplicating a lot of code, but I know some people prefer that for tests, and this seemed in line with the existing tests.
An alternate implementation of this PR could be to implement the `NSURL` methods in terms of `NSString` based file paths, or vice versa.
=> Add methods to create `OHHTPStubResponse`s from `NSURL`s

README.md
If you look at the [rich diff](https://github.com/AliSoftware/OHHTTPStubs/pull/130/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8) it looks much better, and matches the other icons.
=> Use SVG for the Travis CI badge

OHHTTPStubs/Sources/OHHTTPStubs.h, OHHTTPStubs/Sources/OHHTTPStubs.m
The documentation comment for `-onStubActivation:` says that the block can be `nil`:
> Set it to `nil` to do nothing. Defaults is `nil`
The file is within `NS_ASSUME_NONNULL_BEGIN` and `NS_ASSUME_NONNULL_END` so I get a warning 
> :warning: Null passed to a callee that requires a non-null argument
when I pass `nil` for the block parameter.
I have added `nullable` to the method signature to avoid the warning.
=> add `nullable` specifier to block that can be nil

CHANGELOG.md, OHHTTPStubs.podspec, OHHTTPStubs/OHHTTPStubs.xcodeproj/project.pbxproj, OHHTTPStubs/UnitTests/Test Suites/SwiftHelpersTests.swift
This P.R. adds OHHTTPStubsSwift.swift to the Mac Framework and bumps the OSX Deployment Target to 10.9 (i.e. Mavericks).
=> Bumps OS X Deployment Target to 10.9

OHHTTPStubs/Sources/OHHTTPStubs.h, OHHTTPStubs/Sources/OHHTTPStubs.m
Reflects current implementation. This branch does not update the version or run `pod update` for the examples. There is a minor bug in Cocoapods for building projects for different platforms. Not sure how you build your projects so I can add that to the branch when I know what to do. This is in response to https://github.com/AliSoftware/OHHTTPStubs/issues/139
=> Added isEnabled getters for OHHTTPStubs.

CHANGELOG.md, OHHTTPStubs/Sources/Swift/OHHTTPStubsSwift.swift, OHHTTPStubs/UnitTests/Test Suites/SwiftHelpersTests.swift
Added a matcher to check if an NSURLRequest has a header set for a key
Added a matcher to check if an NSURLRequest has a header set for a key and that it's value matches a value passed in.
=> Added 2 matchers for headers 

CHANGELOG.md, OHHTTPStubs/Sources/OHHTTPStubs.m, OHHTTPStubs/UnitTests/Test Suites/AFNetworkingTests.m, OHHTTPStubs/UnitTests/Test Suites/NSURLSessionTests.m
The standard behaviour of NSURLSession, when its delegate says not to follow redirects, and when no custom NSURLProtocol is managing things is to call the completion block with the actual redirect response, its data, and a nil error.
These commits fix OHHTTPStubsProtocol to implement the same behaviour. The behaviour when the delegate says to follow redirects is unchanged.
Note that [Apple’s CustomHTTPProtocol sample code](https://developer.apple.com/library/ios/samplecode/CustomHTTPProtocol/Introduction/Intro.html) instead completes the redirect response with an NSURLErrorCancelled error, diverging from the standard behaviour.
=> Fix for issue #174 - NSURLSessionTask completion block not called when not following redirects

CHANGELOG.md, OHHTTPStubs.podspec, OHHTTPStubs/OHHTTPStubs.xcodeproj/project.pbxproj, OHHTTPStubs/Sources/NSURLSession/NSMutableURLRequest+HTTPBodyTesting.h, OHHTTPStubs/Sources/NSURLSession/NSMutableURLRequest+HTTPBodyTesting.m, OHHTTPStubs/Sources/NSURLSession/OHHTTPStubs+NSURLSessionConfiguration.m, OHHTTPStubs/Sources/NSURLSession/OHHTTPStubsMethodSwizzling.h, OHHTTPStubs/Sources/NSURLSession/OHHTTPStubsMethodSwizzling.m
This addresses the issue described in https://github.com/AliSoftware/OHHTTPStubs/wiki/Testing-for-the-request-body-in-your-stubs and #52 
It also avoids unnecessary changes to the code under test as the setter and getter for `HTTPBody` can still be used without change in behavior (as far as one can tell). 
The new getter `-[NSURLRequest OHHTTPStubs_HTTPBody]` can be used in your `[OHHTTPStubs stubRequestsPassingTest:withStubResponse:]` to test the `HTTPBody`.
One known issue is that if you set the HTTPBody and later reset it to nil (for whatever reason),`OHHTTPStubs_HTTPBody` will still return the last non-nil value.   
Thanks to @shagedorn for the help on method swizzling.
=> Adds support for HTTPBody during testing when using NSURLSession

OHHTTPStubs/OHHTTPStubs.xcodeproj/project.pbxproj, OHHTTPStubs/Sources/NSURLSession/NSURLRequest+HTTPBodyTesting.h, OHHTTPStubs/Sources/NSURLSession/NSURLRequest+HTTPBodyTesting.m, OHHTTPStubs/Supporting Files/OHHTTPStubsUmbrella.h, OHHTTPStubs/UnitTests/Test Suites/NSURLSessionTests.m
This PR addresses two remaining issues from https://github.com/AliSoftware/OHHTTPStubs/pull/166.
* Renames file and category to improve consistency and avoid misunderstandings
* Adds two test cases:
* using the new method, the http body should be accessibly
* using the native method, the http body should not be accessible (else we didn't need the changes after all)
The renamed file isn't explicitly mentioned in the Podspec, so there's no change in that file. I assume users who have not enabled modules in their project/target will have to import `NSURLRequest+HTTPBodyTesting.h` (or the umbrella header) manually, or is there any other place to put it?
=> HTTP Body Tests

CHANGELOG.md, OHHTTPStubs/OHHTTPStubs.xcodeproj/project.pbxproj
This simplifies the project settings a bit and is required to be used in a universal target (e.g. https://github.com/ishkawa/APIKit/pull/179).
=> Set deployment targets at the project level

.travis.yml
This should stabilize running iOS tests on Travis with Xcode 8. See https://github.com/AliSoftware/OHHTTPStubs/pull/184#issuecomment-232067292 for the original concern.
=> [Travis] Use `build-for-testing` and `test-without-building` build actions on Xcode 8

OHHTTPStubs/OHHTTPStubs.xcodeproj/project.pbxproj
Embedding the libraries is causing packaging archives to an `.ipa` to fail like so:
```
INFO [2016-10-20 22:14:16.77]: ▸ + xcodebuild -exportArchive -exportOptionsPlist /var/folders/qv/8ntp55hd26j0zsrdt5tshr900000gn/T/gym_config20161020-99083-8ecbyq.plist -archivePath '/Users/kylejm/Library/Developer/Xcode/Archives/2016-10-20/Loot Release 2016-10-20 22.09.51.xcarchive' -exportPath /var/folders/qv/8ntp55hd26j0zsrdt5tshr900000gn/T/gym_output20161020-99083-i6w8o4
INFO [2016-10-20 22:14:17.97]: ▸ 2016-10-20 22:14:17.976 xcodebuild[99721:3856687] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/qv/8ntp55hd26j0zsrdt5tshr900000gn/T/Loot Release_2016-10-20_22-14-17.975.xcdistributionlogs'.
INFO [2016-10-20 22:14:19.06]: ▸ …
```
=> Switching ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to No

OHHTTPStubs/Sources/Swift/OHHTTPStubsSwift.swift, OHHTTPStubs/UnitTests/Test Suites/SwiftHelpersTests.swift
Fixes #215 
I wasn't able to figure out a way to run the tests with Swift 3.0 though
=> Add OHHTTPStubs_HTTPBody to URLRequest in Swift 3.0

README.md
Previous documentation was not quite working in Swift, due to:
- String not implicitly casted to NSString / NSObject / AnyObject
- missing external parameter name.
=> Minor documentation update for Swift 3.

.travis.yml, Examples/Swift/AppDelegate.swift, Examples/Swift/MainViewController.swift, Examples/Swift/OHHTTPStubsDemo.xcodeproj/project.pbxproj, Examples/Swift/OHHTTPStubsDemo.xcodeproj/xcshareddata/xcschemes/OHHTTPStubsDemo.xcscheme, Examples/Swift/Pods/Pods.xcodeproj/project.pbxproj, OHHTTPStubs/OHHTTPStubs.xcodeproj/project.pbxproj, OHHTTPStubs/Sources/Swift/OHHTTPStubsSwift.swift, OHHTTPStubs/UnitTests/Test Suites/SwiftHelpersTests.swift, README.md
This pull request is mostly a merge of the `swift-3.0` branch to implement #233 :
- it makes `master` use Swift 3.0 as default.
- it fixes some string warnings in some logs from Xcode 8.3.
Once this is merged we will create a `swift-2.3` branch to allow users to use the legacy Swift version if they need it.
❓~One thing I am wondering is if the Travis CI configuration should not be updated in this PR to test both Xcode 8.3 and Xcode 8.2?
Maybe at least change the `osx_image` to `xcode8.3` instead of `xcode8` which from [travis' documentation](https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version) targets some Xcode 8 GM~ 🙄 
The build matrix has been updated to use Xcode 8.3.
A language badge has been added to the [`README`](https://github.com/AliSoftware/OHHTTPStubs/blob/000b57e2 …
=> Xcode 8.3 and Swift 3.x support

README.md
The link to the article seems to be offline. I replaced it with a cached version on archive.org.
=> Replace InfiniteLoop.dk URL with archive.org URL

CHANGELOG.md, OHHTTPStubs/Sources/Swift/OHHTTPStubsSwift.swift
Also added an explanation of which part it is in an example URL.
Add preconditions so that user are better informed of why their requests are not stubbed.
This also adds information of what is a scheme, host or path in the documentation of each matcher.
This will help users see why their matchers setup does not work (see #247).
=> Add precondition assertions in scheme, host matchers

CHANGELOG.md, OHHTTPStubs/UnitTests/Test Suites/MocktailTests.m, OHHTTPStubs/UnitTests/Test Suites/NSURLSessionTests.m
NSURLSession documentation states:
“Important: The session object keeps a strong reference
to the delegate until your app explicitly invalidates the
session. If you do not invalidate the session, your app
leaks memory.”
http://tinyurl.com/jnb6642
- [ X ] I've checked that all new and existing tests pass
- [N/A] I've updated the documentation if necessary
- [ X] I've added an entry in the CHANGELOG to credit myself
NSURLSessions can leak according to the Apple docs. So I've fixed the tests that use them.
Fixed a test that was failing (not due to my changes). "Task created in a session that has been invalidated"
I've removed some invalid whitespace (caught by our own Gerrit). 
Memory leaks which can contribute to unexpected and hard to diagnose improper test behavior.
I ran the tests in …
=> In Test cases, Fix potential memory leaks by use of NSURLSession

CHANGELOG.md, OHHTTPStubs/Sources/HTTPMessage/OHHTTPStubsResponse+HTTPMessage.m, OHHTTPStubs/Sources/JSON/OHHTTPStubsResponse+JSON.m, OHHTTPStubs/Sources/Mocktail/OHHTTPStubs+Mocktail.m, OHHTTPStubs/Sources/OHHTTPStubs.m, OHHTTPStubs/Sources/OHHTTPStubsResponse.m, OHHTTPStubs/UnitTests/Test Suites/AFNetworkingTests.m, OHHTTPStubs/UnitTests/Test Suites/MocktailTests.m, OHHTTPStubs/UnitTests/Test Suites/NSURLConnectionDelegateTests.m, OHHTTPStubs/UnitTests/Test Suites/NSURLConnectionTests.m, OHHTTPStubs/UnitTests/Test Suites/NSURLSessionTests.m, OHHTTPStubs/UnitTests/Test Suites/NilValuesTests.m, OHHTTPStubs/UnitTests/Test Suites/OHPathHelpersTests.m, OHHTTPStubs/UnitTests/Test Suites/SwiftHelpersTests.swift, OHHTTPStubs/UnitTests/Test Suites/TimingTests.m, OHHTTPStubs/UnitTests/Test Suites/WithContentsOfURLTests.m
Remove unnecessary whitespace from empty lines in the test classes.
Future merge issues. Adheres to the already high standard of OHHTTPStubs
Ran all of the tests. 100% passing.
=> Remove whitespace from empty lines in the test classes

CHANGELOG.md, OHHTTPStubs/Sources/Swift/OHHTTPStubsSwift.swift, OHHTTPStubs/UnitTests/Test Suites/SwiftHelpersTests.swift
This PR adds a matcher for the url matcher
Sometimes it's useful to match urls by the absolute url
I've created a test to changes the changes and run all the test 100% success
=> Add Absolute url matcher

CHANGELOG.md, OHHTTPStubs/Sources/OHHTTPStubs.h, OHHTTPStubs/Sources/OHHTTPStubs.m
Add onStubMissing to report missing stubs; detects "stale" stubs which can lead to intermittent failures.
We've been using a fork with this change at Capital One for several months. It's been a big help in solving previously mysterious test failures, where if a stub was missing a request would go to a live server with inconsistent results. It has also helped us visualize our API usage in a different way, for example noticing when a request is made only intermittently or under specific conditions.
Tested by... a) Using it at Capital One for several months, getting hit hundreds, if not thousands, of times per day. b) Ran existing unit tests, and they all passed. c) Did not add a unit test for this feature, since didn't see unit tests for the other debug blocks.
=> Add onStubMissing to report missing stubs; detects "stale" stubs which can lead to intermittent failures

CHANGELOG.md, OHHTTPStubs/Sources/Swift/OHHTTPStubsSwift.swift, OHHTTPStubs/UnitTests/Test Suites/SwiftHelpersTests.swift
I've added a matcher called `hasJsonBody` that  tests whether the `NSURLRequest` body contains a JSON object with the same keys and values.
Since it shouldn't matter in what way the attributes of a JSON object are ordered, trying to match the URL request's body using `hasBody` isn't very handy when it comes to verifying JSON content. That is why I've created a matcher that takes a JSON object and matches is with whatever JSON object it can find in the URL request's body.
I've added two methods in `SwiftHelpersTests.swift` that test a handful of scenarios. Please check them out and let me know if you think I overlooked some important scenarios
=> Add matcher "hasJsonBody"

CHANGELOG.md, OHHTTPStubs/UnitTests/Test Suites/NSURLSessionTests.m, README.md
Updating Readme with known issue.
Changelog.
Disabling flaky tests and updating README with the known issue.
There has been an issue with redirects for several years that seems to be caused by an Apple bug.  This issue has been investigated multiple times, and the path that we want to take forward is to disable the buggy test and update the README with the known issue. 
Discussion on this topic has been mostly happening in #230 and #280 .
=> Disabling troublesome unit test.

CHANGELOG.md, OHHTTPStubs/Sources/OHHTTPStubs.m, OHHTTPStubs/UnitTests/Test Suites/NSURLSessionTests.m
The change in https://github.com/AliSoftware/OHHTTPStubs/pull/263 means a redirected request had the same headers as the original request (because it was a copy and not a brand new `NSURLRequest` instance).
While the new behavior was correct, it didn't account for "special headers" that URLSession "handles". The docs aren't entirely clear what that means, but we've at least confirmed it removes the "Authorization" headers as that poses a security risk, so this PR removes all those headers + a test.
=> Drop special headers from redirected requests

.travis.yml, CHANGELOG.md, Examples/Swift/MainViewController.swift, Examples/Swift/OHHTTPStubsDemo.xcodeproj/project.pbxproj, Examples/Swift/OHHTTPStubsDemo.xcodeproj/xcshareddata/xcschemes/OHHTTPStubsDemo.xcscheme, Examples/Swift/Pods/Pods.xcodeproj/project.pbxproj, OHHTTPStubs.podspec, OHHTTPStubs/OHHTTPStubs.xcodeproj/project.pbxproj, OHHTTPStubs/OHHTTPStubs.xcodeproj/xcshareddata/xcschemes/OHHTTPStubs Mac Framework.xcscheme, OHHTTPStubs/OHHTTPStubs.xcodeproj/xcshareddata/xcschemes/OHHTTPStubs iOS Framework.xcscheme, OHHTTPStubs/OHHTTPStubs.xcodeproj/xcshareddata/xcschemes/OHHTTPStubs iOS StaticLib.xcscheme, OHHTTPStubs/OHHTTPStubs.xcodeproj/xcshareddata/xcschemes/OHHTTPStubs tvOS Framework.xcscheme, OHHTTPStubs/Pods/Pods.xcodeproj/project.pbxproj, OHHTTPStubs/UnitTests/Test Suites/NSURLSessionTests.m, README.md
I have update Swift default version to 5.0
Updating project to Swift 5.0 removes a Carthage warning when updating packages using XCode 10.2.
```
***  Skipped installing OHHTTPStubs.framework binary due to the error:
"Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3).
```
I built OHHTPPStubs using Carthage using Swift 5.0. Warning is not longer appearing. Also I verified the changes did not break any existing unit test.
=> Update Swift 5

CHANGELOG.md, Sources/OHHTTPStubsSwift/OHHTTPStubsSwift.swift, Tests/OHHTTPStubsSwiftTests/SwiftHelpersTests.swift
I've added a matcher called `hasFormBody` that tests whether the `NSURLRequest` content-type is `application/x-www-form-urlencoded` and body contains query parameters.
In POST request with `application/x-www-form-urlencoded`, parameters are handled in httpBody.
For that reason, `containsQueryParams` function is useless for this situation.
Also for the same reason as #265, I need a new matcher that takes query items from httpBody and matches with expected pairs.
=> Add matcher `hasFormBody`

CHANGELOG.md, Package@swift-5.swift
…#328
Fix warning in Xcode 12. _The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99._
To fix warning in Xcode 12
#328
Runned tests in iOS lib and build Examples/SwiftPackageManager.
=> Fix warning in Xcode 12

CHANGELOG.md, Sources/OHHTTPStubsSwift/OHHTTPStubsSwift.swift, Tests/OHHTTPStubsSwiftTests/SwiftHelpersTests.swift
Export OHHTTPStubs from OHHTTPStubsSwift using [`@_exported`](https://github.com/apple/swift/blob/main/docs/ReferenceGuides/UnderscoredAttributes.md#_exported) so that users doesn't need to import both of them.
Previously SwiftPM users should import both OHHTTPStubs and OHHTTPStubsSwift, contrary to CocoaPods users who need to import only OHHTTPStubs.
This difference is small but an obstacle for migrating to Swift Package Manager.
1. Firstly I removed `import OHHTTPStubs` statement from Tests/OHHTTPStubsSwiftTests/SwiftHelperTests.swift. This change made tests fail.
2. Then add `@_exported` modifier to import statement, then the test passed.
=> Export OHHTTPStubs from OHHTTPStubsSwift

CHANGELOG.md, OHHTTPStubs.xcodeproj/project.pbxproj
- [ X ] I've checked that all new and existing tests pass
- [ X ] I've updated the documentation if necessary
- [ X ] I've added an entry in the CHANGELOG to credit myself
On Xcode 13.3 sometimes an error about cycle dependencies is emitted.
The fix to this is to put the Headers build phase before Sources build
phase.
=> OHHTPStubs frameworks: Put Headers phase before Sources phase.
